@startuml


package System {


  actor User
  actor Admin

 
  usecase "Регистрация" as UC1
  usecase "Авторизация" as UC2
  usecase "Просмотр контента" as UC3
  usecase "Управление контентом" as UC4


  User --> UC1
  User --> UC2
  User --> UC3
  Admin --> UC4

}

@enduml
